@api_url = http://localhost:5000

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzOGJhMGJjMy0xZmYwLTQzMTgtYjMyYy04OWE5N2RhZTY3MjQiLCJ1bmlxdWVfbmFtZSI6ImhvcnRlbmN5IiwibmJmIjoxNzQyNjEzNjExLCJleHAiOjE3NDI3MDAwMTEsImlhdCI6MTc0MjYxMzYxMX0.er_XqVOdnvpER8tmxypclGcXC67zvP9JL2rMGOIHWC8

### Registrar um novo usuário
POST {{api_url}}/api/account/register
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="fullName"

Horlência Flores
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

hortency@gmail.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

123456Bb*
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="userName"

hortency
------WebKitFormBoundary7MA4YWxkTrZu0gW--
Content-Disposition: form-data; name="profileImage"; filename="avatar.jpeg"
Content-Type: image/jpeg

< C:\develop\avatar.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--



### Registrar um novo usuário
POST {{api_url}}/api/account/register
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="fullName"

Dexter Fontes
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

dexter@gmail.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

123456Bb*
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="userName"

dex
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="profileImage"; filename="avatar.jpeg"
Content-Type: image/jpeg

< C:\develop\avatar.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Fazer login
POST {{api_url}}/api/account/login
Content-Type: application/json

{
  "email": "hortency@gmail.com",
  "password": "123456Bb*"
}


### get current user details
GET {{api_url}}/api/account/me
Authorization: Bearer {{access_token}}
